project:
  type: website
  output-dir: docs
website:
  title: "Krzysztof Nowak"
  navbar:
    left:
      - text: "Technologies"
        href: Technologies.qmd
    tools:
      - icon: github
        menu:
          - text: Source Code
            href: https://code.com
          - text: Report a Bug
            href: https://bugs.com

format:
  html:
    theme: A calm blue sky
    css: styles.css
    toc: true

editor: visual
